# Generated by Django 2.2 on 2021-05-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='book',
            name='age',
        ),
        migrations.RemoveField(
            model_name='book',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='book',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='book', max_length=255),
            preserve_default=False,
        ),
    ]
